# This is a basic workflow that is manually triggered 

name: 01-manual-input-workflow

# Controls when the action iwll run, Workflow runs when manually triggered using  the UI
# or API.
on: 
  workflow_dispatch:
    # Input the workflow accepts.
    inputs:
      name: 
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is ecplicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequently or in parallel 
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # THe type of runner that thejob will run on
    rund-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
